# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/CodesPractice/learning/DL/FPGA-project-STG/stg_project/stg_project.srcs/sources_1/ip/playerhit_dist_mem/playerhit_dist_mem.xci
# IP: The module: 'playerhit_dist_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CodesPractice/learning/DL/FPGA-project-STG/stg_project/stg_project.gen/sources_1/ip/playerhit_dist_mem/playerhit_dist_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'playerhit_dist_mem'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/CodesPractice/learning/DL/FPGA-project-STG/stg_project/stg_project.srcs/sources_1/ip/playerhit_dist_mem/playerhit_dist_mem.xci
# IP: The module: 'playerhit_dist_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CodesPractice/learning/DL/FPGA-project-STG/stg_project/stg_project.gen/sources_1/ip/playerhit_dist_mem/playerhit_dist_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'playerhit_dist_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
