set_property SRC_FILE_INFO {cfile:d:/CodesPractice/learning/DL/FPGA-project-STG/stg_project/stg_project.gen/sources_1/ip/moon_dist_mem/moon_dist_mem/moon_dist_mem_in_context.xdc rfile:../../../../../stg_project.gen/sources_1/ip/moon_dist_mem/moon_dist_mem/moon_dist_mem_in_context.xdc id:1 order:EARLY scoped_inst:moon_unit/moon_unit} [current_design]
set_property SRC_FILE_INFO {cfile:d:/CodesPractice/learning/DL/FPGA-project-STG/stg_project/stg_project.gen/sources_1/ip/hecatia_dist_mem/hecatia_dist_mem/hecatia_dist_mem_in_context.xdc rfile:../../../../../stg_project.gen/sources_1/ip/hecatia_dist_mem/hecatia_dist_mem/hecatia_dist_mem_in_context.xdc id:2 order:EARLY scoped_inst:hecatia_unit/hecatia_unit} [current_design]
set_property SRC_FILE_INFO {cfile:d:/CodesPractice/learning/DL/FPGA-project-STG/stg_project/stg_project.gen/sources_1/ip/player_dist_mem/player_dist_mem/player_dist_mem_in_context.xdc rfile:../../../../../stg_project.gen/sources_1/ip/player_dist_mem/player_dist_mem/player_dist_mem_in_context.xdc id:3 order:EARLY scoped_inst:player_unit/player_unit} [current_design]
set_property SRC_FILE_INFO {cfile:d:/CodesPractice/learning/DL/FPGA-project-STG/stg_project/stg_project.gen/sources_1/ip/laser_dist_mem/laser_dist_mem/laser_dist_mem_in_context.xdc rfile:../../../../../stg_project.gen/sources_1/ip/laser_dist_mem/laser_dist_mem/laser_dist_mem_in_context.xdc id:4 order:EARLY scoped_inst:laser_unit/laser_unit} [current_design]
set_property SRC_FILE_INFO {cfile:d:/CodesPractice/learning/DL/FPGA-project-STG/stg_project/stg_project.gen/sources_1/ip/background_blk_mem/background_blk_mem/background_blk_mem_in_context.xdc rfile:../../../../../stg_project.gen/sources_1/ip/background_blk_mem/background_blk_mem/background_blk_mem_in_context.xdc id:5 order:EARLY scoped_inst:background_unit/background_unit} [current_design]
set_property SRC_FILE_INFO {cfile:d:/CodesPractice/learning/DL/FPGA-project-STG/stg_project/stg_project.gen/sources_1/ip/cover_blk_mem/cover_blk_mem/cover_blk_mem_in_context.xdc rfile:../../../../../stg_project.gen/sources_1/ip/cover_blk_mem/cover_blk_mem/cover_blk_mem_in_context.xdc id:6 order:EARLY scoped_inst:cover_unit/cover_unit} [current_design]
set_property SRC_FILE_INFO {cfile:d:/CodesPractice/learning/DL/FPGA-project-STG/stg_project/stg_project.gen/sources_1/ip/playerhit_dist_mem/playerhit_dist_mem/playerhit_dist_mem_in_context.xdc rfile:../../../../../stg_project.gen/sources_1/ip/playerhit_dist_mem/playerhit_dist_mem/playerhit_dist_mem_in_context.xdc id:7 order:EARLY scoped_inst:player_unit/playerhit_unit} [current_design]
set_property SRC_FILE_INFO {cfile:d:/CodesPractice/learning/DL/FPGA-project-STG/stg_project/stg_project.gen/sources_1/ip/success_blk_mem/success_blk_mem/success_blk_mem_in_context.xdc rfile:../../../../../stg_project.gen/sources_1/ip/success_blk_mem/success_blk_mem/success_blk_mem_in_context.xdc id:8 order:EARLY scoped_inst:success_unit/success_unit} [current_design]
set_property SRC_FILE_INFO {cfile:D:/CodesPractice/learning/DL/FPGA-project-STG/STG/Code/constraint.xdc rfile:../../../../../../STG/Code/constraint.xdc id:9} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells moon_unit/moon_unit]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells hecatia_unit/hecatia_unit]
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells player_unit/player_unit]
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells laser_unit/laser_unit]
set_property src_info {type:SCOPED_XDC file:5 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins background_unit/background_unit/clka]
set_property src_info {type:SCOPED_XDC file:5 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells background_unit/background_unit]
set_property src_info {type:SCOPED_XDC file:6 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins cover_unit/cover_unit/clka]
set_property src_info {type:SCOPED_XDC file:6 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells cover_unit/cover_unit]
set_property src_info {type:SCOPED_XDC file:7 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells player_unit/playerhit_unit]
set_property src_info {type:SCOPED_XDC file:8 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins success_unit/success_unit/clka]
set_property src_info {type:SCOPED_XDC file:8 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells success_unit/success_unit]
set_property src_info {type:XDC file:9 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports clk]
set_property src_info {type:XDC file:9 line:3 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]
set_property src_info {type:XDC file:9 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports buzzer]
set_property src_info {type:XDC file:9 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[0]}]
set_property src_info {type:XDC file:9 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[1]}]
set_property src_info {type:XDC file:9 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[2]}]
set_property src_info {type:XDC file:9 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[3]}]
set_property src_info {type:XDC file:9 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[4]}]
set_property src_info {type:XDC file:9 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[5]}]
set_property src_info {type:XDC file:9 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[6]}]
set_property src_info {type:XDC file:9 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[7]}]
set_property src_info {type:XDC file:9 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[8]}]
set_property src_info {type:XDC file:9 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[9]}]
set_property src_info {type:XDC file:9 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[10]}]
set_property src_info {type:XDC file:9 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {rgb[11]}]
set_property src_info {type:XDC file:9 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property src_info {type:XDC file:9 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]
set_property src_info {type:XDC file:9 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS15 [get_ports SW]
set_property src_info {type:XDC file:9 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS15 [get_ports rstn]
set_property src_info {type:XDC file:9 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports PS2_clk]
set_property src_info {type:XDC file:9 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports PS2_data]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells moon_unit/moon_unit]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells hecatia_unit/hecatia_unit]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells player_unit/player_unit]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells laser_unit/laser_unit]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells background_unit/background_unit]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells cover_unit/cover_unit]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells player_unit/playerhit_unit]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells success_unit/success_unit]
