# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/CodesPractice/learning/DL/FPGA-project-STG/stg_project/stg_project.runs/synth_1/.Xil/Vivado-23052-SRZbook/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7k160tffg676-2L
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    d:/CodesPractice/learning/DL/FPGA-project-STG/stg_project/stg_project.gen/sources_1/ip/moon_dist_mem
    d:/CodesPractice/learning/DL/FPGA-project-STG/stg_project/stg_project.gen/sources_1/ip/hecatia_dist_mem
    d:/CodesPractice/learning/DL/FPGA-project-STG/stg_project/stg_project.gen/sources_1/ip/player_dist_mem
    d:/CodesPractice/learning/DL/FPGA-project-STG/stg_project/stg_project.gen/sources_1/ip/laser_dist_mem
    d:/CodesPractice/learning/DL/FPGA-project-STG/stg_project/stg_project.gen/sources_1/ip/background_blk_mem
    d:/CodesPractice/learning/DL/FPGA-project-STG/stg_project/stg_project.gen/sources_1/ip/cover_blk_mem
    d:/CodesPractice/learning/DL/FPGA-project-STG/stg_project/stg_project.gen/sources_1/ip/playerhit_dist_mem
    d:/CodesPractice/learning/DL/FPGA-project-STG/stg_project/stg_project.gen/sources_1/ip/success_blk_mem
  } D:/Xilinx/Vivado/2023.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
      rt::read_verilog -include {
    d:/CodesPractice/learning/DL/FPGA-project-STG/stg_project/stg_project.gen/sources_1/ip/moon_dist_mem
    d:/CodesPractice/learning/DL/FPGA-project-STG/stg_project/stg_project.gen/sources_1/ip/hecatia_dist_mem
    d:/CodesPractice/learning/DL/FPGA-project-STG/stg_project/stg_project.gen/sources_1/ip/player_dist_mem
    d:/CodesPractice/learning/DL/FPGA-project-STG/stg_project/stg_project.gen/sources_1/ip/laser_dist_mem
    d:/CodesPractice/learning/DL/FPGA-project-STG/stg_project/stg_project.gen/sources_1/ip/background_blk_mem
    d:/CodesPractice/learning/DL/FPGA-project-STG/stg_project/stg_project.gen/sources_1/ip/cover_blk_mem
    d:/CodesPractice/learning/DL/FPGA-project-STG/stg_project/stg_project.gen/sources_1/ip/playerhit_dist_mem
    d:/CodesPractice/learning/DL/FPGA-project-STG/stg_project/stg_project.gen/sources_1/ip/success_blk_mem
  } {
      D:/CodesPractice/learning/DL/FPGA-project-STG/stg_project/stg_project.runs/synth_1/.Xil/Vivado-23052-SRZbook/realtime/moon_dist_mem_stub.v
      D:/CodesPractice/learning/DL/FPGA-project-STG/stg_project/stg_project.runs/synth_1/.Xil/Vivado-23052-SRZbook/realtime/hecatia_dist_mem_stub.v
      D:/CodesPractice/learning/DL/FPGA-project-STG/stg_project/stg_project.runs/synth_1/.Xil/Vivado-23052-SRZbook/realtime/player_dist_mem_stub.v
      D:/CodesPractice/learning/DL/FPGA-project-STG/stg_project/stg_project.runs/synth_1/.Xil/Vivado-23052-SRZbook/realtime/laser_dist_mem_stub.v
      D:/CodesPractice/learning/DL/FPGA-project-STG/stg_project/stg_project.runs/synth_1/.Xil/Vivado-23052-SRZbook/realtime/background_blk_mem_stub.v
      D:/CodesPractice/learning/DL/FPGA-project-STG/stg_project/stg_project.runs/synth_1/.Xil/Vivado-23052-SRZbook/realtime/cover_blk_mem_stub.v
      D:/CodesPractice/learning/DL/FPGA-project-STG/stg_project/stg_project.runs/synth_1/.Xil/Vivado-23052-SRZbook/realtime/playerhit_dist_mem_stub.v
      D:/CodesPractice/learning/DL/FPGA-project-STG/stg_project/stg_project.runs/synth_1/.Xil/Vivado-23052-SRZbook/realtime/success_blk_mem_stub.v
      D:/CodesPractice/learning/DL/FPGA-project-STG/STG/Code/FSM.v
      D:/CodesPractice/learning/DL/FPGA-project-STG/STG/Code/background.v
      D:/CodesPractice/learning/DL/FPGA-project-STG/STG/Framework/clkdiv_25MHz.v
      D:/CodesPractice/learning/DL/FPGA-project-STG/STG/Code/cover.v
      D:/CodesPractice/learning/DL/FPGA-project-STG/STG/Code/hecatia.v
      D:/CodesPractice/learning/DL/FPGA-project-STG/STG/Code/judge_collision.v
      D:/CodesPractice/learning/DL/FPGA-project-STG/STG/Code/judge_hit.v
      D:/CodesPractice/learning/DL/FPGA-project-STG/STG/Framework/keyboard.v
      D:/CodesPractice/learning/DL/FPGA-project-STG/STG/Code/laser.v
      D:/CodesPractice/learning/DL/FPGA-project-STG/STG/Code/moon.v
      D:/CodesPractice/learning/DL/FPGA-project-STG/STG/Framework/music_room.v
      D:/CodesPractice/learning/DL/FPGA-project-STG/STG/Code/player.v
      D:/CodesPractice/learning/DL/FPGA-project-STG/STG/Code/success.v
      D:/CodesPractice/learning/DL/FPGA-project-STG/STG/Framework/vgac.v
      D:/CodesPractice/learning/DL/FPGA-project-STG/STG/Code/top.v
    }
      rt::read_vhdl -lib xpm D:/Xilinx/Vivado/2023.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList D:/CodesPractice/learning/DL/FPGA-project-STG/stg_project/stg_project.runs/synth_1/.Xil/Vivado-23052-SRZbook/realtime/Top_module_synth.xdc
    rt::sdcChecksum
    set rt::top Top_module
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {D:/CodesPractice/learning/DL/FPGA-project-STG/stg_project/stg_project.cache/wt}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "D:/CodesPractice/learning/DL/FPGA-project-STG/stg_project/stg_project.runs/synth_1/.Xil/Vivado-23052-SRZbook/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    rt::set_parameter incrementalOnCache ""
    rt::set_parameter doIncremental false
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
