# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/CodesPractice/learning/DL/FPGA-project-STG/STG/Code/constraint.xdc

# IP: ip/cover_blk_mem/cover_blk_mem.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cover_blk_mem || ORIG_REF_NAME==cover_blk_mem} -quiet] -quiet
